version: '3'

services:
    stockapi:
        build:
            context: .
            dockerfile: Dockerfile
        image: node:latest
        container_name: stockapi
        restart: unless-stopped
        environment:
            - DATABASE_URL=postgresql://postgres:10203010@192.168.1.200:5432/stockapi
        ports:
            - '3333:3333'
        volumes:
            - .:/home/node/stockapi
