services:
    app:
        build: .
        command: yarn start
        ports:
            - 3333:3333
        environment:
            DATABASE_URL: postgresql://postgres:10203010@192.168.1.200:5432/stockapi
