services:
    app:
        build: .
        command: yarn build
        ports:
            - 3000:3000
        environment:
            DATABASE_URL: postgresql://postgres:050401@localhost:5432/postgres
